# fly.toml app configuration file generated for server-fragrant-dream-7341 on 2024-11-09T16:15:51+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'server-fragrant-dream-7341'
primary_region = 'hkg'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
